#!/bin/bash
# basado en el script de instalación y construcción de elastix 4 en centos 7 de sam

# Desactivar selinux y deshabilitar el firewall si está en funcionamiento.
setenforce 0
sed -i 's/\(^selinux=\).*/\selinux=disabled/' /etc/selinux/config

# Algunas distribuciones pueden ya tener un grupo asterisk existente. Se crea aquí
# si el grupo no existe aún (con la opción -f).
/usr/sbin/groupadd -f -r asterisk

# En este punto, el grupo asterisk ya debe existir
if ! grep -q asterisk: /etc/passwd ; then
    echo -e "agregando nuevo usuario asterisk..."
    /usr/sbin/useradd -r -g asterisk -c "asterisk pbx" -s /bin/bash -d /var/lib/asterisk asterisk
fi

# Descargar issabel y prepararlo para la instalación
if [[ $(which wget) = "" ]]; then
        yum install -y wget
fi
sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/c*.repo
sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/c*.repo
sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/c*.repo
yum -y update
sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/c*.repo
sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/c*.repo
sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/c*.repo
yum -y install epel-release
yum -y install htop glances screen fail2ban-server wget sysstat net-tools
yum -y remove fail2ban-firewalld
systemctl enable fail2ban.service
chkconfig fail2ban on
sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/c*.repo
sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/c*.repo
sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/c*.repo
yum -y update
sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/c*.repo
sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/c*.repo
sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/c*.repo

if [ `swapon -s | wc | awk '{print $1}'` = 0 ]; then
if [ ! -f /swapfile ]; then
dd if=/dev/zero of=/swapfile bs=1024 count=1024k
chown root:root /swapfile
chmod 0600 /swapfile
mkswap /swapfile
swapon /swapfile
echo "/swapfile          swap            swap    defaults        0 0" >> /etc/fstab
sysctl vm.swappiness=10
echo vm.swappiness=10 >> /etc/sysctl.conf
free -h
cat /proc/sys/vm/swappiness
fi
fi
cd /tmp
cat > /etc/yum.repos.d/issabel.repo <<eof
[issabel-base]
name=base rpm repository for issabel
mirrorlist=http://mirror.issabel.org/?release=4&arch=\$basearch&repo=base
#baseurl=http://repo.issabel.org/issabel/4/base/\$basearch/
gpgcheck=0
enabled=1
gpgkey=http://repo.issabel.org/issabel/rpm-gpg-key-issabel

[issabel-updates]
name=updates rpm repository for issabel
mirrorlist=http://mirror.issabel.org/?release=4&arch=\$basearch&repo=updates
#baseurl=http://repo.issabel.org/issabel/4/updates/\$basearch/
gpgcheck=0
enabled=1
gpgkey=http://repo.issabel.org/issabel/rpm-gpg-key-issabel

[issabel-updates-sources]
name=updates rpm repository for issabel
mirrorlist=http://mirror.issabel.org/?release=4&arch=\$basearch&repo=updates
#baseurl=http://repo.issabel.org/issabel/4/updates/srpms/
gpgcheck=0
enabled=1
gpgkey=http://repo.issabel.org/issabel/rpm-gpg-key-issabel

[issabel-beta]
name=beta rpm repository for issabel
mirrorlist=http://mirror.issabel.org/?release=4&arch=\$basearch&repo=beta
baseurl=http://repo.issabel.org/issabel/4/beta/\$basearch/
#gpgcheck=1
enabled=0
#gpgkey=http://repo.issabel.org/issabel/rpm-gpg-key-issabel

[issabel-extras]
name=extras rpm repository for issabel
mirrorlist=http://mirror.issabel.org/?release=4&arch=\$basearch&repo=extras
#baseurl=http://repo.issabel.org/issabel/4/extras/\$basearch/
gpgcheck=1
enabled=1
gpgkey=http://repo.issabel.org/issabel/rpm-gpg-key-issabel

eof
cat > /tmp/inst1.txt <<eof
acl
apr
apr-util
audit
audit-libs
authconfig
autogen-libopts
basesystem
bash
bind-libs-lite
bind-license
binutils
biosdevname
btrfs-progs
bzip2-libs
ca-certificates
centos-logos
centos-release
chkconfig
chrony
compat-libtiff3
coreutils
cpio
cracklib
cracklib-dicts
cronie
cronie-noanacron
crontabs
cryptsetup-libs
cups-libs
curl
cyrus-imapd
cyrus-imapd-utils
cyrus-sasl
cyrus-sasl-lib
cyrus-sasl-plain
dbus
dbus-glib
dbus-libs
dbus-python
dhclient
dhcp
dhcp-common
dhcp-libs
dialog
diffutils
dmidecode
dnsmasq
dracut
dracut-config-rescue
dracut-network
e2fsprogs
e2fsprogs-libs
ebtables
elfutils-libelf
elfutils-libs
epel-release
ethtool
expat
festival
festival-lib
festival-speechtools-libs
festvox-slt-arctic-hts
file
file-libs
filesystem
findutils
fipscheck
fipscheck-lib
firewalld
flac-libs
fontconfig
fontpackages-filesystem
freetype
fxload
gawk
gdbm
gdbm-devel
gettext
gettext-libs
ghostscript
ghostscript-fonts
glib2
glibc
glibc-common
glibc-devel
glibc-headers
glib-networking
gmp
gnupg2
gnutls
gobject-introspection
gpgme
gpm-libs
grep
groff-base
grub2
grub2-efi
grub2-tools
grubby
gsettings-desktop-schemas
gsm
gzip
hardlink
hdparm
hostname
httpd
httpd-tools
hwdata
info
initscripts
iproute
iprutils
iptables
iptables-services
iptables-devel
iputils
irqbalance
jansson
jbigkit-libs
json-c
kbd
kbd-misc
kernel
kernel-devel
kernel-headers
kernel-tools
kernel-tools-libs
kexec-tools
keyutils-libs
kpartx
krb5-libs
lcms2
less
libacl
libaio
libao
libassuan
libasyncns
libattr
libblkid
libcap
libcap-ng
libcom_err
libcroco
libcurl
libdaemon
libdb
libdb-devel
libdb-utils
libdrm
libedit
libestr
libffi
libfontenc
libgcc
libgcrypt
libgomp
libgpg-error
libgudev1
libice
libidn
libjpeg-turbo
libmnl
libmodman
libmount
libndp
libnetfilter_conntrack
libnfnetlink
libnl3
libnl3-cli
libogg
libpcap
libpciaccess
libpipeline
libpng
libproxy
libpwquality
libreport-filesystem
libselinux
libselinux-python
libselinux-utils
libsemanage
libsepol
libsm
libsndfile
libsoup
libss
libssh2
libstdc++
libsysfs
libtasn1
libteam
libtiff
libtiff-devel
libtiff-tools
libtool-ltdl
libunistring
libusb
libusbx
libuser
libutempter
libuuid
libverto
libvorbis
libx11
libx11-common
libxau
libxcb
libxext
libxfont
libxi
libxml2
libxpm
libxslt
libxt
libxtst
libzip
linux-firmware
lm_sensors-libs
lockdev
logrotate
lua
lvm2
lvm2-libs
lzo
mailcap
mailman
mailx
make
man-db
mariadb
mariadb-libs
mariadb-server
mdadm
memtest86+
mgetty
microcode_ctl
modemmanager-glib
mod_ssl
mokutil
mozjs17
mtools
mysql-python
ncurses
ncurses-base
ncurses-libs
net-snmp-agent-libs
net-snmp-libs
nettle
net-tools
newt
newt-python
nmap
nmap-ncat
nspr
nss
nss-softokn
nss-softokn-freebl
nss-sysinit
nss-tools
nss-util
ntp
ntpdate
numactl-libs
openldap
openssh
openssh-clients
openssh-server
openssl
openssl-libs
opus
os-prober
p11-kit
p11-kit-trust
pam
parted
passwd
pciutils
pciutils-libs
pcre
perl
perl-archive-tar
perl-business-isbn
perl-business-isbn-data
perl-carp
perl-cgi
perl-compress-raw-bzip2
perl-compress-raw-zlib
perl-constant
perl-crypt-openssl-bignum
perl-crypt-openssl-random
perl-crypt-openssl-rsa
perl-data-dumper
perl-date-manip
perl-dbd-mysql
perl-db_file
perl-dbi
perl-devel
perl-digest
perl-digest-hmac
perl-digest-md5
perl-digest-sha
perl-encode
perl-encode-detect
perl-encode-locale
perl-error
perl-exporter
perl-extutils-install
perl-extutils-makemaker
perl-extutils-manifest
perl-extutils-parsexs
perl-fcgi
perl-file-listing
perl-file-path
perl-file-temp
perl-filter
perl-getopt-long
perl-html-parser
perl-html-tagset
perl-http-cookies
perl-http-daemon
perl-http-date
perl-http-message
perl-http-negotiate
perl-http-tiny
perl-io-compress
perl-io-html
perl-io-socket-inet6
perl-io-socket-ip
perl-io-socket-ssl
perl-io-zlib
perl-libs
perl-libwww-perl
perl-lwp-mediatypes
perl-macros
perl-mail-dkim
perl-mail-imapclient
perl-mail-spf
perl-mailtools
perl-netaddr-ip
perl-net-daemon
perl-net-dns
perl-net-http
perl-net-libidn
perl-net-smtp-ssl
perl-net-ssleay
perl-package-constants
perl-parent
perl-parse-recdescent
perl-pathtools
perl-plrpc
perl-pod-escapes
perl-podlators
perl-pod-perldoc
perl-pod-simple
perl-pod-usage
perl-scalar-list-utils
perl-socket
perl-socket6
perl-storable
perl-sys-syslog
perl-test-harness
perl-text-parsewords
perl-threads
perl-threads-shared
perl-timedate
perl-time-hires
perl-time-local
perl-uri
perl-version
perl-www-robotrules
php
php-bcmath
php-cli
php-common
php-gd
php-imap
php-mbstring
php-mcrypt
php-mysql
php-pdo
php-pear
php-process
php-soap
php-tcpdf
php-tidy
php-xml
pinentry
pkgconfig
plymouth
plymouth-core-libs
plymouth-scripts
policycoreutils
polkit
polkit-pkla-compat
poppler-data
popt
portreserve
postfix
postgresql-libs
ppp
procmail
procps-ng
psmisc
pth
pulseaudio-libs
pygobject3-base
pygpgme
pyliblzma
pyopenssl
python
python-backports
python-backports-ssl_match_hostname
python-configobj
python-crypto
python-decorator
python-ecdsa
python-iniparse
python-libs
python-lockfile
python-pycurl
python-pyudev
python-setuptools
python-six
python-slip
python-slip-dbus
python-sqlalchemy
python-tempita
python-urlgrabber
pytz
pyxattr
qrencode-libs
readline
rootfiles
rpm
rpm-build-libs
rpm-libs
rpm-python
rsyslog
sed
selinux-policy
selinux-policy-targeted
setup
shadow-utils
shared-mime-info
sharutils
shim
shim-unsigned
slang
snappy
sox
spamassassin
spandsp
spandsp-devel
speex
sqlite
sudo
syslinux
systemd
systemd-libs
systemd-sysv
systemtap-sdt-devel
sysvinit-tools
t1lib
tar
tcp_wrappers-libs
teamd
tftp-server
tuned
tzdata
unixodbc
urw-fonts
ustr
util-linux
uuid
uuid-perl
vim-common
vim-enhanced
vim-filesystem
vim-minimal
virt-what
vsftpd
wavpack
which
wpa_supplicant
xfsprogs
xinetd
xorg-x11-font-utils
xz
xz-libs
yum
yum-metadata-parser
yum-plugin-fastestmirror
zlib
pv
unzip
certbot
python2-certbot
python2-certbot-apache
eof
cat > /tmp/inst2.txt <<eof
acl
aic94xx-firmware
alsa-firmware
alsa-lib
alsa-tools-firmware
apr
apr-util
asterisk11
asterisk11-addons
asterisk11-devel
asterisk11-perl
asterisk-pt_br-soundspa
asterisk11-sounds-es
asterisk11-sounds-fr
asterisk-codec-g729
audit
audit-libs
authconfig
autogen-libopts
avahi
avahi-autoipd
avahi-libs
basesystem
bash
bind-libs-lite
bind-license
binutils
biosdevname
btrfs-progs
bzip2-libs
ca-certificates
centos-logos
centos-release
chkconfig
chrony
compat-libtiff3
coreutils
cpio
cracklib
cracklib-dicts
cronie
cronie-noanacron
crontabs
cryptsetup-libs
cups-libs
curl
cyrus-imapd
cyrus-imapd-utils
cyrus-sasl
cyrus-sasl-lib
cyrus-sasl-plain
dahdi
dahdi-linux
dbus
dbus-glib
dbus-libs
dbus-python
device-mapper
device-mapper-event
device-mapper-event-libs
device-mapper-libs
device-mapper-persistent-data
dhclient
dhcp
dhcp-common
dhcp-libs
dialog
diffutils
dmidecode
dnsmasq
dracut
dracut-config-rescue
dracut-network
e2fsprogs
e2fsprogs-libs
ebtables
issabel
issabel-system
issabel-framework
issabel-addons
issabel-agenda
issabel-asterisk-sounds
issabel-email_admin
issabel-endpointconfig2
issabel-extras
issabel-fax
issabel-firstboot
issabel-im
issabel-my_extension
issabel-pbx
issabel-portknock
issabel-reports
issabel-security
elfutils-libelf
elfutils-libs
epel-release
ethtool
expat
festival
festival-lib
festival-speechtools-libs
festvox-slt-arctic-hts
file
file-libs
filesystem
findutils
fipscheck
fipscheck-lib
firewalld
flac-libs
fontconfig
fontpackages-filesystem
freepbx
freetype
fxload
gawk
gdbm
gdbm-devel
gettext
gettext-libs
ghostscript
ghostscript-fonts
glib2
glibc
glibc-common
glibc-devel
glibc-headers
glib-networking
gmp
gnupg2
gnutls
gobject-introspection
gpgme
gpm-libs
grep
groff-base
grub2
grub2-efi
grub2-tools
grubby
gsettings-desktop-schemas
gsm
gzip
hardlink
hdparm
hostname
httpd
httpd-tools
hwdata
hylafax
iaxmodem
iksemel
info
initscripts
iproute
iprutils
iptables
iptables-services
iptables-devel
iputils
irqbalance
ivtv-firmware
iwl1000-firmware
iwl100-firmware
iwl105-firmware
iwl135-firmware
iwl2000-firmware
iwl2030-firmware
iwl3160-firmware
iwl3945-firmware
iwl4965-firmware
iwl5000-firmware
iwl5150-firmware
iwl6000-firmware
iwl6000g2a-firmware
iwl6000g2b-firmware
iwl6050-firmware
iwl7260-firmware
jansson
jbigkit-libs
json-c
kbd
kbd-misc
kernel
kernel-devel
kernel-headers
kernel-tools
kernel-tools-libs
kexec-tools
keyutils-libs
kpartx
krb5-libs
lcdissabel
lcdproc
lcms2
less
libacl
libaio
liballogsmat
libao
libassuan
libasyncns
libattr
libblkid
libcap
libcap-ng
libc-client
libcom_err
libcroco
libcurl
libdaemon
libdb
libdb-devel
libdb-utils
libdrm
libedit
libertas-sd8686-firmware
libertas-sd8787-firmware
libertas-usb8388-firmware
libestr
libffi
libfontenc
libgcc
libgcrypt
libgomp
libgpg-error
libgsmat
libgudev1
libice
libidn
libjpeg-turbo
libmcrypt
libmnl
libmodman
libmount
libndp
libnetfilter_conntrack
libnfnetlink
libnl3
libnl3-cli
libogg
libopenr2
libpcap
libpciaccess
libpipeline
libpng
libpri
libproxy
libpwquality
libreport-filesystem
libselinux
libselinux-python
libselinux-utils
libsemanage
libsepol
libsm
libsndfile
libsoup
libsrtp
libss
libss7
libssh2
libstdc++
libsysfs
libtasn1
libteam
libtidy
libtiff
libtiff-devel
libtiff-tools
libtool-ltdl
libunistring
libusb
libusbx
libuser
libutempter
libuuid
libverto
libvorbis
libwat
libx11
libx11-common
libxau
libxcb
libxext
libxfont
libxi
libxml2
libxpm
libxslt
libxt
libxtst
libzip
linux-firmware
lm_sensors-libs
lockdev
logrotate
lua
lvm2
lvm2-libs
lzo
mailcap
mailman
make
man-db
mariadb
mariadb-libs
mariadb-server
mdadm
memtest86+
mgetty
microcode_ctl
modemmanager-glib
mod_ssl
mokutil
mozjs17
mtools
mysql-python
mysql-to-mariadb-server
ncurses
ncurses-base
ncurses-libs
net-snmp-agent-libs
net-snmp-libs
nettle
net-tools
newt
newt-python
nmap
nmap-ncat
nspr
nss
nss-softokn
nss-softokn-freebl
nss-sysinit
nss-tools
nss-util
ntp
ntpdate
numactl-libs
openfire
openldap
openssh
openssh-clients
openssh-server
openssl
openssl-libs
opus
os-prober
p11-kit
p11-kit-trust
pam
parted
passwd
pciutils
pciutils-libs
pcre
perl
perl-archive-tar
perl-business-isbn
perl-business-isbn-data
perl-carp
perl-cgi
perl-compress-raw-bzip2
perl-compress-raw-zlib
perl-constant
perl-convert-binhex
perl-crypt-openssl-bignum
perl-crypt-openssl-random
perl-crypt-openssl-rsa
perl-data-dumper
perl-date-manip
perl-dbd-mysql
perl-db_file
perl-dbi
perl-devel
perl-digest
perl-digest-hmac
perl-digest-md5
perl-digest-sha
perl-encode
perl-encode-detect
perl-encode-locale
perl-error
perl-exporter
perl-extutils-install
perl-extutils-makemaker
perl-extutils-manifest
perl-extutils-parsexs
perl-fcgi
perl-file-listing
perl-file-path
perl-file-temp
perl-filter
perl-getopt-long
perl-html-parser
perl-html-tagset
perl-http-cookies
perl-http-daemon
perl-http-date
perl-http-message
perl-http-negotiate
perl-http-tiny
perl-io-compress
perl-io-html
perl-io-socket-inet6
perl-io-socket-ip
perl-io-socket-ssl
perl-io-zlib
perl-libs
perl-libwww-perl
perl-lwp-mediatypes
perl-macros
perl-mail-dkim
perl-mail-imapclient
perl-mail-spf
perl-mailtools
perl-mime-tools
perl-netaddr-ip
perl-net-daemon
perl-net-dns
perl-net-http
perl-net-libidn
perl-net-smtp-ssl
perl-net-ssleay
perl-package-constants
perl-parent
perl-parse-recdescent
perl-pathtools
perl-plrpc
perl-pod-escapes
perl-podlators
perl-pod-perldoc
perl-pod-simple
perl-pod-usage
perl-scalar-list-utils
perl-socket
perl-socket6
perl-storable
perl-sys-syslog
perl-test-harness
perl-text-parsewords
perl-threads
perl-threads-shared
perl-timedate
perl-time-hires
perl-time-local
perl-uri
perl-version
perl-www-robotrules
php
php-bcmath
php-cli
php-common
php-gd
php-idna_convert
php-imap
php-jpgraph
php-magpierss
php-mbstring
php-mcrypt
php-mysql
php-pdo
php-pear
php-pear-db
php-phpmailer
php-process
php-simplepie
php-smarty
php-soap
php-tcpdf
php-tidy
php-xml
pinentry
pkgconfig
plymouth
plymouth-core-libs
plymouth-scripts
policycoreutils
polkit
polkit-pkla-compat
poppler-data
popt
portreserve
postfix
postgresql-libs
ppp
procmail
procps-ng
psmisc
pth
pulseaudio-libs
py-asterisk
pygobject3-base
pygpgme
pyliblzma
pyopenssl
python
python-backports
python-backports-ssl_match_hostname
python-cjson
python-configobj
python-crypto
python-daemon
python-decorator
python-ecdsa
python-eventlet
python-greenlet
python-iniparse
python-libs
python-lockfile
python-paramiko
python-pycurl
python-pyudev
python-setuptools
python-six
python-slip
python-slip-dbus
python-sqlalchemy
python-tempita
python-urlgrabber
pytz
pyxattr
qrencode-libs
readline
rhino
rootfiles
roundcubemail
rpm
rpm-build-libs
rpm-libs
rpm-python
rsyslog
sed
selinux-policy
selinux-policy-targeted
setup
shadow-utils
shared-mime-info
sharutils
shim
shim-unsigned
slang
snappy
sox
spamassassin
spandsp
spandsp-devel
speex
sqlite
sudo
syslinux
systemd
systemd-libs
systemd-sysv
systemtap-sdt-devel
sysvinit-tools
t1lib
tar
tcp_wrappers-libs
teamd
tftp-server
tuned
tzdata
unixodbc
urw-fonts
ustr
util-linux
uuid
uuid-perl
vim-common
vim-enhanced
vim-filesystem
vim-minimal
virt-what
vsftpd
wanpipe-util
wavpack
which
wpa_supplicant
xfsprogs
xinetd
xorg-x11-font-utils
xz
xz-libs
yum
yum-metadata-parser
yum-plugin-fastestmirror
zlib
gcc
gcc-c++
automake
unzip
pv
zip
wget
iptables-devel
perl-text-csv_xs
certbot
python2-certbot
python2-certbot-apache
eof
yum clean all
yum -y update
sleep 3
yum -y --nogpg install $(cat /tmp/inst1.txt)
sleep 3
systemctl enable mariadb.service
systemctl start mariadb
mysql -e "set password for 'root'@'localhost' = password('issabel.2o24')"
yum -y install asterisk11
yum -y install issabel
# Ejecutar una segunda vez en caso de que se haya perdido algo
yum -y --nogpg install $(cat /tmp/inst2.txt)
yum clean all
yum -y update

# Desactivar selinux y el firewall. Asegúrate de configurarlo en elastix!
setenforce 0
sed -i 's/\(^selinux=\).*/\selinux=disabled/' /etc/selinux/config
cp -a /etc/sysconfig/iptables /etc/sysconfig/iptables.org-issabel-"$(/bin/date "+%y-%m-%d-%h-%m-%s")"
systemctl enable httpd
systemctl disable firewalld
systemctl stop firewalld
firewall-cmd --zone=public --add-port=443/tcp --permanent
firewall-cmd --reload
rm -f /etc/issabel.conf
mysql -pissabel.2o24 -e "set password for 'root'@'localhost' = password('')"

# Parchear archivos de configuración
echo "noload => cdr_mysql.so" >> /mnt/sysimage/etc/asterisk/modules_additional.conf
echo " " >> /mnt/sysimage/etc/asterisk/res_odbc_additional.conf
echo " " >> /mnt/sysimage/etc/asterisk/res_odbc_custom.conf
mv /etc/asterisk/extensions_custom.conf.sample /etc/asterisk/extensions_custom.conf

chown -r asterisk.asterisk /var/www/html
chown -r asterisk.asterisk /etc/asterisk
chown -r asterisk.asterisk /var/lib/asterisk
mkdir -p /var/log/asterisk
mkdir -p /var/log/asterisk/cdr-csv
chown -r asterisk.asterisk /var/log/asterisk
/usr/sbin/amportal chown
mv /etc/asterisk/extensions_custom.conf.sample /etc/asterisk/extensions_custom.conf
cd /usr/src
wget repo.issabel.org/geoip/geoipdb.tar.gz
wget repo.issabel.org/geoip/geoip_install.sh
wget repo.issabel.org/geoip/xtables-addons-2.12.tar.xz
chmod a+x geoip_install.sh
./geoip_install.sh
cd -
/etc/init.d/issabel-firstboot start
yum update xtables-addons
yum -y install https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
yum install open-vm-tools zabbix-agent2 -y
wget -o - https://github.com/ibinetwork/issabelbr/raw/master/patch-issabelbr.sh | bash
reboot
